### ISSUE TITLE
Add cli argument to specify .env file.

### ISSUE THREAD

**Issue by einnjo** [AndersDJohnson/dotenv-export#3]
The `.env` value seems to be hardcoded, it would be great if we could specify it.

**Comment by AndersDJohnson** [comment]
Sure. Just curious, what do you use?

**Comment by einnjo** [comment]
I have a `.env` file per environment. (.test.env, .development.env, .production.env)

**Comment by AndersDJohnson** [comment]
@juanjoLenero Would you like to pass the filename to use as an argument to the CLI?

**Comment by einnjo** [comment]
Yeah, that would be great!

**Comment by AndersDJohnson** [comment]
@juanjoLenero I've implemented and published with `1.1.0`.

**Comment by AndersDJohnson** [comment]
@juanjoLenero Please star!
