### ISSUE TITLE
Support multiline environment variables

### ISSUE THREAD

**Issue by d4nyll** [AndersDJohnson/dotenv-export#4]
Similar to the [`dotenv`](https://github.com/motdotla/dotenv#rules) package:

* new lines are expanded if in double quotes (`MULTILINE="new\nline"` becomes

      {MULTILINE: 'new
      line'}

**Comment by d4nyll** [comment]
At the moment, I can use the following command to convert `\n` to an actual new line:

    source <(dotenv-export | sed 's/\\n/\n/g')

If you don't wish to add this functionality, maybe it's still worth adding this into the `README.md`

**Comment by AndersDJohnson** [comment]
@d4nyll Would you like to open a PR to update the README with that trick? Or even give an implementation a shot?

**Comment by d4nyll** [comment]
I added a PR #5. I am on holiday now, but might have some time after to write new tests + implement. It'll probably just be an extra function that replaces the `\n` with a new line character.

**Comment by AndersDJohnson** [comment]
I guess #5 doesn't close this, so re-opening.
